sudo: false
language: node_js
node_js:
  - node
  - lts/*
  - '11'
  - '10'
  - '8'
  - '6'

os:
  - osx
  - linux
  - windows

services:
  - xvfb

cache:
  npm: false

install: npm install --ignore-scripts

matrix:
  include:
    - os: windows
      node_js: 'node/x86'
    - os: windows
      node_js: 'lts/*/x86'
    - os: windows
      node_js: '11/x86'
    - os: windows
      node_js: '10/x86'
    - os: windows
      node_js: '8/x86'
    - os: windows
      node_js: '6/x86'

    - os: windows
      env: TEST_NAME="windows-electron@4"
      before_install: npm install electron@4 npx
      script:
        - npx electron --version
        - npx electron .
    - os: linux
      env: TEST_NAME="linux-electron@4"
      before_install: npm install electron@4 npx
      script:
        - xvfb-run --auto-servernum npx electron --version
        - xvfb-run --auto-servernum npx electron .
    - os: osx
      env: TEST_NAME="osx-electron@4"
      before_install: npm install electron@4 npx
      script:
        - npx electron --version
        - npx electron .
    - os: windows
      env: TEST_NAME="windows-electron@5"
      before_install: npm install electron@5 npx
      script:
        - npx electron --version
        - npx electron .
    - os: linux
      env: TEST_NAME="linux-electron@5"
      before_install: npm install electron@5 npx
      script:
        - xvfb-run --auto-servernum npx electron --version
        - xvfb-run --auto-servernum npx electron .
    - os: osx
      env: TEST_NAME="osx-electron@5"
      before_install: npm install electron@5 npx
      script:
        - npx electron --version
        - npx electron .
    - os: windows
      env: TEST_NAME="windows-electron@6"
      before_install: npm install electron@6 npx
      script:
        - npx electron --version
        - npx electron .
    - os: linux
      env: TEST_NAME="linux-electron@6"
      before_install: npm install electron@6 npx
      script:
        - xvfb-run --auto-servernum npx electron --version
        - xvfb-run --auto-servernum npx electron .
    - os: osx
      env: TEST_NAME="osx-electron@6"
      before_install: npm install electron@6 npx
      script:
        - npx electron --version
        - npx electron .
    - os: windows
      env: TEST_NAME="windows-electron@latest"
      before_install: npm install electron@latest npx
      script:
        - npx electron --version
        - npx electron .
    - os: linux
      env: TEST_NAME="linux-electron@latest"
      before_install: npm install electron@latest npx
      script:
        - xvfb-run --auto-servernum npx electron --version
        - xvfb-run --auto-servernum npx electron .
    - os: osx
      env: TEST_NAME="osx-electron@latest"
      before_install: npm install electron@latest npx
      script:
        - npx electron --version
        - npx electron .
